name: Backend Tests

on:
  push:
    branches: [develop]
    paths: ['backend/**']
  pull_request:
    branches: [develop]
    paths: ['backend/**']

jobs:
  test:
    runs-on: windows-latest # Focus on Windows first
    timeout-minutes: 15

    steps:
      # 1. CHECKOUT CODE
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend/
            !**/node_modules/
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      # 2. WINDOWS CONFIG
      - name: Configure Windows
        run: |
          git config --global core.longpaths true
          git config --global core.symlinks false
          net start postgresql-x64-14 || true

      # 3. NODE SETUP
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4. USE YOUR EXISTING DATABASE (No new DB)
      - name: Test Setup
        run: |
          npm ci
          npx prisma generate
          npx prisma migrate dev
        working-directory: ./backend
        env:
          DATABASE_URL: 'postgresql://postgres:elmundoesancho@localhost:5432/taskmanager'

      # 5. RUN TESTS
      - name: Run Tests
        run: npm test
        working-directory: ./backend
        env:
          DATABASE_URL: 'postgresql://postgres:elmundoesancho@localhost:5432/taskmanager'
          CI: true
