name: Frontend Tests

on:
  pull_request:
    paths:
      - 'frontend/**'
    branches: [main, develop]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.longpaths true
          git config --global core.autocrlf input

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            frontend/node_modules
          key: ${{ matrix.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      # Verify Vitest is available
      - name: Check test setup
        run: npx vitest --version || echo "Vitest not found"

      - name: Run tests
        run: npm run test
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096 # Prevent OOM errors
